version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:20.11
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: install-frontend-dependencies
          command: |
            cd crud-todos
            npm install
      - run:
          name: build-frontend
          command: |
            cd crud-todos
            npm run build
      - run:
          name: install-backend-dependencies
          command: |
            cd crud-todos-backend
            npm install
      - run:
          name: build-and-push-docker-image
          command: |
            cd crud-todos-backend
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
            docker build -t $IMAGE_NAME:latest .
            docker push $IMAGE_NAME:latest
      - run:
          name: archive-frontend-build
          command: |
            tar -czf frontend-build.tar.gz -C crud-todos/build .
      - run:
          name: archive-backend
          command: |
            tar -czf backend.tar.gz -C crud-todos-backend .
      - persist_to_workspace:
          root: .
          paths:
            - frontend-build.tar.gz
            - backend.tar.gz
  deploy:
    docker:
      - image: cimg/node:20.11
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "SHA256:m+Ex21QZsb6Guo4aAsuG3tBIcdSs612z1SOoqk9kSB0"
      - run:
          name: deploy-to-ec2
          command: |
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "sudo chown -R ubuntu:ubuntu /var/www/html"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "sudo chmod -R 755 /var/www/html"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "rm -rf /var/www/html/*"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "mkdir -p /home/ubuntu/crud-app/crud-todos"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "mkdir -p /home/ubuntu/crud-app/crud-todos-backend"
            scp -o StrictHostKeyChecking=no frontend-build.tar.gz ubuntu@13.61.122.171:/home/ubuntu/crud-app/
            scp -o StrictHostKeyChecking=no backend.tar.gz ubuntu@13.61.122.171:/home/ubuntu/crud-app/
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "tar -xzf /home/ubuntu/crud-app/frontend-build.tar.gz -C /var/www/html/"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "tar -xzf /home/ubuntu/crud-app/backend.tar.gz -C /home/ubuntu/crud-app/crud-todos-backend/"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "docker pull $IMAGE_NAME:latest"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "docker stop crud-todos-backend || true"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "docker rm crud-todos-backend || true"
            ssh -o StrictHostKeyChecking=no ubuntu@13.61.122.171 "docker run -d --name crud-todos-backend -p 8082:8082 $IMAGE_NAME:latest"
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main