version: 2.1
jobs:
  build_frontend:
    docker:
      - image: cimg/node:16.13
    working_directory: ~/CRUD-app/crud-todos
    steps:
      - checkout
      - run:
          name: Install Frontend Dependencies
          command: npm install
      - run:
          name: Build Frontend
          command: npm run build
      - persist_to_workspace:
          root: ~/CRUD-app/crud-todos
          paths:
            - build

  build_backend:
    docker:
      - image: cimg/node:16.13
    working_directory: ~/CRUD-app/crud-todos-backend
    steps:
      - checkout
      - run:
          name: Install Backend Dependencies
          command: npm install
      - persist_to_workspace:
          root: ~/CRUD-app/crud-todos-backend
          paths:
            - .

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: ~/CRUD-app
      - run:
          name: Deploy Frontend to EC2
          command: |
            scp -r ~/CRUD-app/crud-todos/build ubuntu@51.20.123.183:/var/www/html/
            ssh -o StrictHostKeyChecking=no ubuntu@51.20.123.183 "sudo systemctl restart nginx"
      - run:
          name: Deploy Backend to EC2
          command: |
            scp -r ~/CRUD-app/crud-todos-backend/* ubuntu@51.20.123.183:~/crud-todos-backend/
            ssh -o StrictHostKeyChecking=no ubuntu@51.20.123.183 "cd ~/crud-todos-backend && npm install && pm2 restart app || pm2 start app.js"

workflows:
  build-and-deploy:
    jobs:
      - build_frontend
      - build_backend
      - deploy:
          requires:
            - build_frontend
            - build_backend