version: 2.1 # YML 2.1

workflows:
  version: 2 # CircleCI 2
  build:
    jobs:
      - build: # Tasks we want CircleCI to execute (CI)
          filters:
            branches:
              only: main  # Run CI only on the main branch

jobs:
  build:  # What happens in our build job
    working_directory: ~/ProjectPart2/CRUD-app
    docker:
      - image: circleci/node:16  # Version of node js
    steps:
      - checkout # Clone GitHub repository
      - run:
          name: Update npm # version of npm
          command: 'npm install npm@8'  # Install locally without global update
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}  # Restore dependencies 
      - run:
          name: Install npm dependencies
          command: npm install # Install dependencies 
      - run:
          name: Build Application
          command: npm run build  # Build the React application
        
      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

